apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    app: web
    clusterId: aabb-ccdd-ee
spec:
  containers:
    - name: busybox
      image: docker.io/busybox:latest
      command: ['sleep', '3600000000']
      resources:
        limits:
          cpu: 250m
          memory: 128Mi
 
