apiVersion: v1
kind: Pod
metadata:
  name: redis-django
  labels:
    app: web
spec:
  containers:
    - name: key-value-store
      image: redis
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6379
    - name: mysql
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          # change this
          value: yourpassword
      ports:
        - containerPort: 3306
          name: mysql
    - name: busybox
      image: docker.io/busybox:latest
      command: ['sleep', '36000']
 
